name: apartmantmanager
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  rxdart: ^0.28.0
  qr_code_scanner_plus: ^2.0.6
  #  mobile_scanner: ^5.1.1
  url_launcher: ^6.3.0
  http: ^1.2.2
  intl: ^0.19.0
  get_it: ^7.1.3
  tuple: ^2.0.2
  video_player: ^2.2.19
  #  flutter_credit_card: ^4.0.1
  webview_flutter: ^4.8.0
  lottie: ^3.1.2
  clipboard: ^0.1.3
  easy_localization: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"

flutter:
  uses-material-design: true

  assets:

    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf